services:
  cache-aside:
    build:
      context: .
    command: "npm run cache-aside"
    volumes:
      - ./src:/app
    depends_on:
      - redis
    ports:
      - "3000:3000"
  refresh-ahead:
    build:
      context: .
    command: "npm run refresh-ahead"
    volumes:
      - ./src:/app
    depends_on:
      - redis
    ports:
      - "3001:3000"
  redis:
    image: 'redis:alpine'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
